# Generated by Django 2.2 on 2019-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pmfd',
            new_name='pmfdt',
        ),
    ]
